# Generated by Django 4.1.3 on 2022-12-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_manager",
            "0002_project_team_alter_task_options_alter_worker_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                related_name="projects", to="task_manager.team"
            ),
        ),
    ]
