# Generated by Django 4.1.3 on 2022-12-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_alter_project_teams"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_team_name",
        ),
    ]
