# Generated by Django 4.1.3 on 2022-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_remove_team_unique_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
