# Generated by Django 4.1.3 on 2022-12-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0008_remove_profile_id_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
    ]
