# Generated by Django 4.1.3 on 2022-12-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0010_alter_task_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="project",
            new_name="projects",
        ),
    ]
