# Generated by Django 4.1.3 on 2022-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0012_alter_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                null=True, related_name="projects", to="task_manager.team"
            ),
        ),
    ]
